apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: us-central1-docker.pkg.dev/triple-grove-438014-p9/artifact-repo/flask-app:$COMMIT_SHA
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
